config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from mhms.users.views import student_register, hostel_application, admin_dashboard_view

urlpatterns = [
    path("",
         TemplateView.as_view(template_name="hostel/index.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path("student-register", student_register, name="student-registration"),
    path("apply", hostel_application, name="apply"),
    path("admin-dashboard", admin_dashboard_view, name="admin-dashboard"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # Custom admin template
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    # User management
    path("users/", include("mhms.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

mhms/users/urls.py
from django.urls import path

from mhms.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

mhms/users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, TextChoices, Model, OneToOneField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.db import models


class User(AbstractUser):
    """Default user for MOUAU Hostel Management System."""

    class Types(TextChoices):
        ADMIN = "ADMIN", "Admin"
        STUDENT = "STUDENT", "Student"
        PORTAL = "PORTAL", "Portal"

    type = CharField(
        _("Type"), max_length=50, choices=Types.choices, default=Types.STUDENT
    )
    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})


################--------- Model managers goes here --------- ####################

#############----------- Model manager --------------- #########################

class AdminManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.ADMIN)


class PortalManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.PORTAL)


class StudentManager(BaseUserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Types.STUDENT)


################---------End of Model managers --------- ####################


########### Administrator proxy model and Attributes ----------------#######################


class AdminAttributes(Model):
    user = OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        upload_to="profile_pic/DoctorProfilePic/", null=True, blank=True
    )
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20, null=True)
    status = models.BooleanField(default=False)

    @property
    def get_name(self):
        return self.user.first_name + " " + self.user.last_name

    @property
    def get_id(self):
        return self.user.id

    def __str__(self):
        return f"{self.user}"


class Admin(User):
    objects = AdminManager()

    @property
    def doc_details(self):
        return self.adminattributes

    class Meta:
        proxy = True

    def save(
        self,
        *args,
        **kwargs,
    ):
        if not self.pk:
            self.type = User.Types.ADMIN
        return super().save(*args, **kwargs)


########### End of Administrator proxy model and Attributes ----------------#######################

########### Portal proxy model and Attributes ----------------#######################


class PortalAttributes(Model):
    user = OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        upload_to="profile_pic/PortalProfilePic/", null=True, blank=True
    )
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20, null=True)
    status = models.BooleanField(default=False)

    @property
    def get_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def get_id(self):
        return self.user.id

    def __str__(self):
        return f"{self.user.name}"


class Portal(User):
    objects = PortalManager()

    @property
    def doc_details(self):
        return self.portalattributes

    class Meta:
        proxy = True

    def save(
        self,
        *args,
        **kwargs,
    ):
        if not self.pk:
            self.type = User.Types.PORTAL
        return super().save(*args, **kwargs)


########### End of Portal proxy model and Attributes ----------------#######################


########### Hostel and Room model and ----------------###################################


class Room(models.Model):
    room_num = models.IntegerField(_("Room number"))
    occupied = models.BooleanField(_("Is the room occupied?"), default=False)

    class RoomCondition(TextChoices):
        GOOD = "GOOD", "Good"
        BAD = "BAD", "Bad"
        MAINTENANCE = "MAINTENANCE", "Maintenance"
    room_condition = models.CharField(
        _("Room condition"),
        choices=RoomCondition.choices,
        max_length=50, default=RoomCondition.GOOD)
    occupants = models.ForeignKey(
        "PortalAttributes",
        verbose_name=_("Room occupants"),
        on_delete=models.CASCADE)

    class RoomStatus(TextChoices):
        FULL = "FULL", "Full"
        EMPTY = "EMPTY", "Empty"
    room_status = models.CharField(
        _("Is the room full or empty"),
        max_length=50, choices=RoomStatus.choices, default=RoomStatus.EMPTY)
    total_bed_space = models.IntegerField(
        _("Total bed spaces"), default=8)

    def __str__(self):
        return f"{self.room_num}"


class Hostel(models.Model):
    name = models.CharField(
        _("Hostel name"),
        max_length=50)
    portal = models.ForeignKey(
        "Portal",
        verbose_name=_("Hostel Portal"),
        on_delete=models.CASCADE)
    description = models.CharField(
        _("Brief description"),
        max_length=500)
    GENDER_CHOICES = [
        ('m', 'Male'),
        ('f', 'Female'),
    ]
    gender = models.CharField(
        _("Male or Female"),
        max_length=1,
        choices=GENDER_CHOICES)
    room_spaces = models.PositiveSmallIntegerField(default=20)

    def __str__(self):
        return f"{self.name}"

########### End of Hostel and Room model ----------------###################################


########### Student proxy model and Attributes ----------------#######################

class Level(models.Model):
    name = models.CharField(verbose_name="Student Level", max_length=5)

    def __str__(self):
        return self.name


class College(models.Model):
    name = models.CharField(verbose_name="Student College", max_length=50)

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(verbose_name="Student Department", max_length=100)

    def __str__(self):
        return self.name


class StudentAttributes(Model):
    user = OneToOneField(User, on_delete=models.CASCADE)
    reg_num = models.CharField(verbose_name="Registration Number", max_length=100, default='MOUAU/19/78765')
    level = OneToOneField(Level, on_delete=models.CASCADE, related_name="student_level")
    college = OneToOneField(College, on_delete=models.CASCADE, related_name="student_college")
    department = OneToOneField(Department, on_delete=models.CASCADE, related_name="student_department")
    hostel_allocated = OneToOneField("Hostel", on_delete=models.CASCADE, related_name="hostel_allocated")
    room = OneToOneField("Room", on_delete=models.CASCADE, related_name="room_allocated", null=True)
    # status = models.CharField(verbose_name="Is the student verified or not", choices=)
    payment_status = models.BooleanField(verbose_name="Student payment status", null=True)
    payment_date = models.DateTimeField(auto_now_add=False, null=True)
    profile_pic = models.ImageField(
        upload_to="profile_pic/DoctorProfilePic/", null=True, blank=True
    )
    address = models.CharField(max_length=40, help_text="Home Address")
    mobile = models.CharField(max_length=20, null=True)
    status = models.BooleanField(default=False)

    @property
    def get_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    @property
    def get_id(self):
        return self.user.id

    def __str__(self):
        return f"{self.user} "


class Student(User):
    objects = StudentManager()

    @property
    def doc_details(self):
        return self.portalattributes

    class Meta:
        proxy = True

    def save(
        self,
        *args,
        **kwargs,
    ):
        if not self.pk:
            self.type = User.Types.STUDENT
        return super().save(*args, **kwargs)


###########____________________ End of Student proxy model and Attributes ----------------#######################


###########_____________________ Hostel application model ----------------#######################

class HostelApplicationModel(models.Model):
    student = OneToOneField("Student", on_delete=models.CASCADE)
    hostel = OneToOneField("Hostel", on_delete=models.CASCADE)
    room = OneToOneField("Room", on_delete=models.CASCADE)

###########_____________________End of Hostel application model ----------------#######################

mhms/users/forms.py
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from mhms.users.models import StudentAttributes, HostelApplicationModel

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class StudentUserForm(ModelForm):
    class Meta:
        model = User
        fields = ["name", "email", "password", "username"]
        widgets = {"password": forms.PasswordInput()}


class StudentRegisterForm(ModelForm):
    class Meta:
        model = StudentAttributes
        fields = ["reg_num", "level", "college", "department", "address", "mobile", "profile_pic"]


class HostelApplication(ModelForm):
    class Meta:
        model = HostelApplicationModel
        fields = ["hostel", "room"]

mhms/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

from mhms.users.forms import StudentUserForm, StudentRegisterForm, HostelApplication
from mhms.users.models import Room, Student, Hostel, Portal

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


def student_register(request):
    student_user_form = StudentUserForm()
    student_reg_form = StudentRegisterForm()
    mydict = {'student_user_form': student_user_form, 'student_reg_form': student_reg_form}
    if request.method == 'POST':
        student_user_form = StudentUserForm(request.POST)
        print(student_user_form)
        student_reg_form = StudentRegisterForm(request.POST, request.FILES)
        print(student_reg_form)
        if student_user_form.is_valid() and student_reg_form.is_valid():
            user = student_user_form.save()
            user.set_password(user.password)
            user.save()
            student = student_reg_form.save(commit=False)
            student.user = user
            # student.assignedDoctorId = request.POST.get('assignedDoctorId')
            student = student.save()
        return HttpResponseRedirect('student-login')
    return render(request, 'users/signup.html', context=mydict)


def student_login(request):
    pass


def hostel_application(request):
    hostel_application_form = HostelApplication()
    mydict = {'hostel_application_form': hostel_application_form}
    if request.method == 'POST':
        hostel_application_form = HostelApplication(request.POST)
        print(hostel_application_form)
        if hostel_application_form.is_valid():
            hostel_app = hostel_application_form.save()
        return HttpResponseRedirect('application-success')
    return render(request, 'users/apply.html', context=mydict)


def admin_dashboard_view(request):
    student_count = Student.objects.all().count()
    staff_count = Portal.objects.all().count()
    total_rooms = Room.objects.all().count()
    rooms_available = Room.objects.all().filter(occupied=False).count()

    occupied_rooms = Room.objects.all().filter(occupied=True).count()
    mydict = {
        'student_count': student_count,
        'staff_count': staff_count,
        'total_rooms': total_rooms,
        'rooms_available': rooms_available,
        'occupied_rooms': occupied_rooms,
    }
    return render(request, 'hostel/index.html', context=mydict)

mhms/templates/users/apply.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
{#  <h1>{{ user.username }}</h1>#}
  <br>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
          <div class="form-group">
    {% render_field hostel_application_form.hostel class="form-control" placeholder="Choose a hostel" %}
          </div>
    <div class="form-group">
              {% render_field hostel_application_form.room class="form-control" placeholder="Choose a Room" %}
                  </div>
      <div class="form-group">
        {% render_field student_user_form.name class="form-control" placeholder="Full Name" %}
      </div>
     <div class="form-group">
              {% render_field student_user_form.password class="form-control" placeholder="Password" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.reg_num class="form-control" placeholder="Password" %}
              </div>
      <div class="form-group">
              {% render_field student_reg_form.level class="form-control" placeholder="Level" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.college class="form-control" placeholder="College" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.department class="form-control" placeholder="Department" %}
              </div>
      <div class="form-group">
              {% render_field student_reg_form.address class="form-control" placeholder="Address" %}
              </div>
      <div class="form-group">
              {% render_field student_reg_form.mobile class="form-control" placeholder="Mobile" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.profile_pic class="form-control" placeholder="Profile Picture" %}
              </div>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

mhms/templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
{#  <h1>{{ user.username }}</h1>#}
  <br>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
          <div class="form-group">
    {% render_field student_user_form.username class="form-control" placeholder="Username" %}
          </div>
    <div class="form-group">
              {% render_field student_user_form.email class="form-control" placeholder="Email" %}
                  </div>
      <div class="form-group">
        {% render_field student_user_form.name class="form-control" placeholder="Full Name" %}
      </div>
     <div class="form-group">
              {% render_field student_user_form.password class="form-control" placeholder="Password" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.reg_num class="form-control" placeholder="Password" %}
              </div>
      <div class="form-group">
              {% render_field student_reg_form.level class="form-control" placeholder="Level" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.college class="form-control" placeholder="College" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.department class="form-control" placeholder="Department" %}
              </div>
      <div class="form-group">
              {% render_field student_reg_form.address class="form-control" placeholder="Address" %}
              </div>
      <div class="form-group">
              {% render_field student_reg_form.mobile class="form-control" placeholder="Mobile" %}
              </div>
    <div class="form-group">
              {% render_field student_reg_form.profile_pic class="form-control" placeholder="Profile Picture" %}
              </div>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

mhms/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}